// You are given two strings, s and t which only consist of lowercase letters.
// t is generated by shuffling the letters in s as well as potentially adding
// an additional random character. Return the letter that was randomly added to t
// if it exists, otherwise, return ’ ‘.
// Note: You may assume that at most one additional character can be added to t.

// Ex: Given the following strings...

// s = "foobar", t = "barfoot", return 't'
// s = "ide", t = "idea", return 'a'
// s = "coding", t "ingcod", return ''

const charCount = (ch, inputstr) => {
  //   return [...inputstr].reduce((acc, c) => (c === ch ? ++acc : acc), 0);
  return inputstr.split(ch).length - 1;
};

const spotTheDifference = (s, t) => {
  const sCharMap = {};
  const tCharMap = {};
  s.split("").forEach((ch) => (sCharMap[ch] = charCount(ch, s)));
  t.split("").forEach((ch) => (tCharMap[ch] = charCount(ch, t)));

  for (let ch of t) if (!sCharMap[ch] || sCharMap[ch] < tCharMap[ch]) return ch;
  return "";
};

const test = () => {
  testCases = [
    { s: "foobar", t: "barfoot" },
    { s: "ide", t: "idea" },
    { s: "coding", t: "ingcod" },
    { s: "eye", t: "yeee" },
  ];
  expecteds = ["t", "a", "", "e"];

  for (let i = 0; i < testCases.length; i++) {
    const actual = spotTheDifference(testCases[i].s, testCases[i].t);
    console.log(`For '${testCases[i]}' output obtained '${actual}'`);
    console.assert(
      actual == expecteds[i],
      `Wrong answer. Expected: '${expecteds[i]}'. Found: '${actual}'`
    );
  }
  console.log("Test completed.");
};

test();
